### ISSUE TITLE
Cannot read journal file

### ISSUE THREAD

**Issue by tonyedgecombe** [mariosangiorgio/vscode-ledger#7]
Every time I open a .ledger file I get an error: 

    Cannot read journal file "/c%3A/path/to/ledger/file.ledger"

This is running 1.08 on VSCode 1.13.1 on Windows 10.

**Comment by jeevcat** [comment]
I have the same problem. Looks like it might be due to the way the Windows path is being converted to a POSIX(?) path. The colon shouldn't be percent encoded, but discarded.

**Comment by mariosangiorgio** [comment]
Thanks for reporting the issue. I don't have a Windows box to test this on so it's not surprising I haven't noticed this issue earlier.

I'm going to be away for the next two weeks. After that I'll have a look and hopefully fix the issue. I believe @jeevcat is right so the fix shouldn't be too hard.

**Comment by mariosangiorgio** [comment]
@tonyedgecombe can you please try if version 1.0.9 solves the issue and let me know?

I think I'm using the proper URI parser ([`vscode-uri`](https://github.com/Microsoft/vscode-uri)) but I haven't had a chance to test the change on Windows so there might be still something missing.

**Comment by ghost** [comment]
I now get:

    Error: Cannot read journal file "/cygdrive/c/data/repos/ledger_personal/c:\data\repos\ledger_personal\2017-06.ledger"

**Comment by mariosangiorgio** [comment]
I didn't realise ledger requires cygwin to run on Windows. Anyway, with the changes I applied yesterday we're now using an absolute Windows path and the behaviour of the extension seems correct to me.

I think that now you're experiencing the same issue reported [here](https://github.com/AlexanderAA/ledger_binaries_windows/issues/3). Maybe we can check with them if there is a way to make the Windows executable work as expected.

If not we can think how we could work around this issue from within the extension.

**Comment by sachpatel** [comment]
I have 1.09 running. I have set my `ledger.binary` settings key to `/c/tools/ledger` or `/cygdrive/c/tools/ledger` where ledger is in that folder and the version of ledger is `Ledger 3.1.1-20150915`

In VS Code when opening a *.ledger file in the editor, I see the following printed to the OUTPUT terminal
```events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn /cygdrive/c/tools/ledger ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
[Info  - 13:39:19] Connection to server got closed. Server will restart.
events.js:160
      throw er; // Unhandled 'error' event
      ^```

**Comment by ghost** [comment]
Yes, that was the problem, I wrote a little stub program to manipulate the path before it gets to ledger as it turns out just compiling it on Windows is a ton of work. Thanks for your help.

**Comment by sachpatel** [comment]
@tonyedgecombe Would you mind sharing your solution? I would love to get this extension functioning correctly with Ledger I am running on Windows.

**Comment by ghost** [comment]
https://github.com/tonyedgecombe/ledgerfix
